feat: create put api to edit proposal relates #111
CA-G12/g-lancer pull request #114
Opened 2022-10-25 13:11 UTC by shathakh

2022-10-25 13:19 UTC, mohammedagha27 approved these changes

2022-10-25 14:32 UTC, alishanti98 approved these changes

2022-10-25 19:13 UTC, LinaYahya requested changes

2022-10-25 19:13 UTC, LinaYahya commented on server/src/controllers/proposals.ts
> +  const proposal = await Proposal.findByPk(id);
try to check in there's no proposal in the first place

2022-10-26 06:51 UTC, LinaYahya approved these changes

2022-10-26 08:54 UTC, naghamabuwarda approved these changes

2022-10-26 11:00 UTC, merged