feat: edit job card actions relates #105
CA-G12/g-lancer pull request #115
Opened 2022-10-25 13:29 UTC by naghamabuwarda

2022-10-25 19:17 UTC, LinaYahya requested changes

2022-10-25 19:17 UTC, LinaYahya commented on client/src/pages/JobsSearch/index.tsx
> +                ? (
not sure what is the point of the ternary operator here?

2022-10-26 06:44 UTC, LinaYahya requested changes

2022-10-26 06:44 UTC, LinaYahya commented on client/src/components/jobCard/index.tsx
> +          {user?.userID === job.userId && <DeleteIcon />}
```suggestion
          {user?.userID === job.userId && (job.isOccupied === false) && <DeleteIcon />}
```

2022-10-26 08:23 UTC, mohammedagha27 approved these changes

2022-10-26 08:31 UTC, LinaYahya approved these changes

2022-10-26 08:35 UTC, alishanti98 approved these changes

2022-10-26 09:20 UTC, shathakh approved these changes

2022-10-26 09:20 UTC, merged