feat: create POST/ login Api and its tests
CA-G12/g-lancer pull request #121
Opened 2022-10-26 09:41 UTC by mohammedagha27

close #120

2022-10-26 18:11 UTC, LinaYahya requested changes

2022-10-26 18:11 UTC, LinaYahya commented on server/src/helpers/jwt.ts
> +dotenv.config();
```suggestion
```
No need to import it every where as import it at the app level will expose it where we need

2022-10-26 18:11 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +  if (!user) return { status: 400, msg: 'User not found' };
```suggestion
  if (!user) throw serverErrs.BadReq
```
Also, I'd prefer to send hazy message, that email or password incorrect
Read more on [Authentication and error messages](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-and-error-messages)

2022-10-26 18:11 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +const loginMiddleware = async (req: Request, res: Response) => {
```suggestion
const login = async (req: Request, res: Response) => {
```

2022-10-27 04:30 UTC, naghamabuwarda approved these changes

2022-10-27 08:00 UTC, shathakh approved these changes

2022-10-27 10:42 UTC, LinaYahya approved these changes

2022-10-27 10:42 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +  return { status: 200, msg: 'logged in successfully' };
I think we will need to return values needed to be set at `UserContext`, For now we will leave it and we can fix when we send request at login page

2022-10-27 10:53 UTC, merged