feat: add the third step of sign up relates #118
CA-G12/g-lancer pull request #123
Opened 2022-10-27 01:09 UTC by naghamabuwarda

2022-10-28 13:55 UTC, LinaYahya requested changes
Good Job @naghamabuwarda ,
I've noticed that we create image as required in the `Freelancer` model,
Can you fix it please?

2022-10-28 13:55 UTC, LinaYahya commented on package.json
> +    "@mui/lab": "^5.0.0-alpha.105"
It's already installed at `client`

2022-10-28 13:55 UTC, LinaYahya commented on server/src/controllers/jobs.ts
> +  const JOBS_PER_PAGE = 5;
Not sure why is that?

2022-10-28 13:55 UTC, LinaYahya commented on client/src/validation/index.ts
> +  Title: yup
```suggestion
  title: yup // as it is in the freelancer model
```

2022-10-28 13:55 UTC, LinaYahya commented on client/src/validation/index.ts
> +  Major: yup
```suggestion
major: yup
```

2022-10-28 13:55 UTC, LinaYahya commented on client/src/validation/index.ts
> +  description: yup
```suggestion
  brief: yup
```

2022-10-28 13:55 UTC, LinaYahya commented on client/src/pages/Signup/index.tsx
> +import { FirstStep, Signup, ThirdStepSignUp } from '../../components';
```suggestion
import { FirstStep, Signup, ThirdStepSignUp } from '../../components';
```
I think we can give it more descriptive name

2022-10-28 13:55 UTC, LinaYahya commented on client/src/components/signup/index.tsx
> +function ThirdStepSignUp() {
Why not to separate in another file!

2022-10-28 13:55 UTC, LinaYahya commented on client/src/components/signup/index.tsx
> +            <div style={{
why not to give it a classname and then style it in the `css` file

2022-10-30 06:32 UTC, LinaYahya approved these changes

2022-10-30 07:56 UTC, mohammedagha27 approved these changes

2022-10-30 09:13 UTC, shathakh approved these changes

2022-10-30 09:13 UTC, alishanti98 approved these changes

2022-10-30 09:13 UTC, merged