feat: create sign up api for user relates #125
CA-G12/g-lancer pull request #126
Opened 2022-10-27 11:50 UTC by shathakh

2022-10-28 14:01 UTC, LinaYahya requested changes
Just Great Job
@shathakh  🥳

2022-10-28 14:01 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +  return { status: 200, data: 'signed up successfully ' };
```suggestion
  return { status: 201, data: 'signed up successfully ' };
```

2022-10-28 14:01 UTC, LinaYahya commented on server/src/validation/index.ts
> +  role: yup.string().required(),
validated based on the two options we have

2022-10-30 09:48 UTC, mohammedagha27 approved these changes

2022-10-30 09:48 UTC, naghamabuwarda approved these changes

2022-10-30 09:48 UTC, LinaYahya approved these changes

2022-10-30 09:49 UTC, merged