102 react create the client dashboard page and include its components
CA-G12/g-lancer pull request #128
Opened 2022-10-27 15:34 UTC by alishanti98

2022-10-29 18:20 UTC, LinaYahya requested changes

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +  const acceptPropsal = async (proposalID: number, jobID: number) => {
```suggestion
  const acceptProposal = async (proposalID: number, jobID: number) => {
```

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +    setOpenAlertproposal(true);
this will run even before response was recieved

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +      setLoading(false);
When you set loading true so, you set it `false` here,
Many errors can happen, I suppose that there's a better way of handling error!

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +      </Stack>
No need to have 2 snackbars, as it a component I can control when to open and what the message would be

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +  const [openAlertProposal, setOpenAlertproposal] = useState(false);
Really not sure why to have all these states, and I think names you used doesn't clarify whats the point of them,
Use more descriptive names

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +  const handleDelete = async (idItem: number) => {
delete a job, delete a proposal?

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +    setOpenAlert(true);
this will run even before response was recieved

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +          <Alert severity="success">
I think alert may run in case of error, SO severity would be different try to use it to handle possible errors

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +                {job.proposals.map((proposal) => <ProposalJob proposal={proposal} acceptProposal={acceptPropsal} />)}
a key is required here

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +          <JobCard job={job} deleteItem={handleDelete} key={job.title}>
```suggestion
          <JobCard job={job}  key={job.title}> // I think no way to delete accepted job
```

2022-10-29 18:20 UTC, LinaYahya commented on client/src/pages/Client/index.tsx
> +        {jobsOccupied.map((job) => (
I can see that we repeat ouselves in both in `occupeied` and `unoccupied` jobs,
May be we can create a component to handle this

2022-10-29 18:20 UTC, LinaYahya commented on client/src/components/addJobForm/index.tsx
> +          },
try to console.log values, You may noticed that it is the same object we're creating here

2022-10-29 18:20 UTC, LinaYahya commented on client/src/components/addJobForm/index.tsx
> +        console.log(err);
```suggestion
        console.log(err); // eror handling is a must
```

2022-10-29 18:20 UTC, LinaYahya commented on client/src/components/addJobForm/index.tsx
> +        formik.resetForm();
Also we need to close the modal when the response succeeded

2022-10-30 19:38 UTC, shathakh approved these changes

2022-10-31 08:00 UTC, mohammedagha27 approved these changes

2022-10-31 10:44 UTC, naghamabuwarda approved these changes

2022-10-31 10:45 UTC, merged