feat: freelancer sign up with test relates #127
CA-G12/g-lancer pull request #129
Opened 2022-10-27 15:59 UTC by naghamabuwarda

2022-10-28 14:16 UTC, LinaYahya requested changes

2022-10-28 14:16 UTC, LinaYahya commented on server/src/validation/index.ts
> +  Title: yup
```suggestion
  title: yup
```

2022-10-28 14:16 UTC, LinaYahya commented on server/src/validation/index.ts
> +  Major: yup
```suggestion
  major: yup
```

2022-10-28 14:16 UTC, LinaYahya commented on server/src/validation/index.ts
> +  description: yup
```suggestion
  brief: yup
```

2022-10-28 14:16 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +  if (!user) throw serverErrs.BAD_REQUEST('user id doen\'t exist');
```suggestion
  if (!user) throw serverErrs.BAD_REQUEST('Something went wrong');
```

2022-10-28 14:16 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +    Title, Major, portfolio, description, image, id,
```suggestion
   title, major, portfolio, brief, image, userId,
```

2022-10-28 14:16 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +  const token = await generateToken({ userID: id, role, name });
First we have to `create` into freelancer model,
then we can generate token, specially that token `id` is freelancer id not `userId`

2022-10-28 14:16 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +  await freelancerValidate.validate(req.body);
validation goes first

2022-10-28 14:16 UTC, LinaYahya commented on server/src/controllers/authentication.ts
> +  return { status: 200, data: freelancer, msg: 'successful login' };
```suggestion
  return { status: 201, data: freelancer, msg: 'successful login' };
```
And I think we don't need the whole data `name`, `role`, and freelancer `id` would be enough

2022-10-30 07:24 UTC, LinaYahya approved these changes

2022-10-30 07:56 UTC, mohammedagha27 approved these changes

2022-10-30 09:14 UTC, alishanti98 approved these changes

2022-10-30 09:14 UTC, shathakh approved these changes

2022-10-30 09:15 UTC, merged