124 freelancer page
CA-G12/g-lancer pull request #130
Opened 2022-10-29 09:51 UTC by mohammedagha27

2022-10-30 10:06 UTC, LinaYahya requested changes

2022-10-30 18:06 UTC, LinaYahya requested changes

2022-10-30 18:06 UTC, LinaYahya commented on client/src/pages/Freelancer/index.tsx
> +  const onUpdate = async (values: ProposalProps, proposalId: number) => {
```suggestion
  const updateProposalHandler = async (values: ProposalProps, proposalId: number) => {
```

2022-10-30 18:06 UTC, LinaYahya commented on client/src/pages/Freelancer/index.tsx
> +  const onDelete = async (proposalId: number) => {
```suggestion
  const deleteProposal = async (proposalId: number) => {
```

2022-10-31 10:27 UTC, shathakh approved these changes

2022-10-31 10:28 UTC, alishanti98 approved these changes

2022-10-31 10:44 UTC, naghamabuwarda approved these changes

2022-10-31 13:49 UTC, merged