feat: create server with express
CA-G12/g-lancer pull request #27
Opened 2022-10-11 17:02 UTC by alishanti98

relates #21

2022-10-12 07:24 UTC, shathakh approved these changes

2022-10-12 09:36 UTC, LinaYahya requested changes
Good Job Ali,
I would prefer to use morgan as a logger middleware try to search about and find away to use it
[morgan](https://github.com/expressjs/morgan#readme)

2022-10-12 09:36 UTC, LinaYahya commented on server/routes/index.ts
> +const Router = express.Router()
```suggestion
const router = express.Router()
```

2022-10-12 09:36 UTC, LinaYahya commented on server/app.ts
> +dotenv.config();
remove to top level,
before calling express

2022-10-12 09:36 UTC, LinaYahya commented on server/app.ts
> +app.use(express.json());
`app.use()` takes a series of middlewares as an array, 
so I prefer to use it in that way
```js
app.use([cookieParser(), compression(), ..etc]);
```

2022-10-12 09:36 UTC, LinaYahya commented on server/routes/index.ts
> +const Router = express.Router()
```suggestion
const Router = express.Router()
```

2022-10-12 11:40 UTC, LinaYahya commented on server/index.ts
> +app.listen(port, () => {
let us sync sequelize before listening to the server

2022-10-12 16:35 UTC, mohammedagha27 approved these changes

2022-10-13 06:27 UTC, naghamabuwarda approved these changes

2022-10-13 06:28 UTC, mohammedagha27 approved these changes

2022-10-13 07:43 UTC, LinaYahya approved these changes

2022-10-13 07:43 UTC, merged