feat: create error handlers and custome error relates #34
CA-G12/g-lancer pull request #35
Opened 2022-10-12 18:03 UTC by shathakh

2022-10-12 19:35 UTC, mohammedagha27 approved these changes

2022-10-13 05:02 UTC, alishanti98 approved these changes

2022-10-13 07:05 UTC, naghamabuwarda approved these changes

2022-10-13 08:18 UTC, LinaYahya requested changes
Good job Shatha, 
please import customerr ans serverErr at `helprs/index` and import from there,
Also use error middleware at express app

2022-10-13 08:18 UTC, LinaYahya commented on server/middlewares/error.ts
> +  next(); // error eslint next defined but never used
```suggestion
```
There's no next here

2022-10-13 08:18 UTC, LinaYahya commented on server/middlewares/error.ts
> +const serverError = (err: any, req: Request, res: Response, next: NextFunction) => {
```suggestion
const serverError: : ErrorRequestHandler = (err, req, res, next) => {
```

2022-10-13 08:54 UTC, LinaYahya approved these changes

2022-10-13 08:55 UTC, merged