feat: create job card component relates #41
CA-G12/g-lancer pull request #43
Opened 2022-10-14 08:28 UTC by shathakh

2022-10-15 10:29 UTC, LinaYahya requested changes
Great Job Shatha!
Just small notes to take

2022-10-15 10:29 UTC, LinaYahya commented on client/src/components/jobCard/jobCard.tsx
> +              style={{
It'll be exhausting to us to style every button in the app, instead, we can create an app theme in the `app` and change colors `primary` and `secondray` and pass theme to the app, Then all of our app will apply that theme
Check [createTheme API](https://mui.com/material-ui/customization/theming/#createtheme-options-args-theme)

2022-10-15 10:29 UTC, LinaYahya commented on client/src/components/jobCard/jobCard.tsx
> +          <Link to="/job/jobid">
why not to add `onClick` button handler and then navigate to the desired route
check [useNavigate API](https://reactrouter.com/en/main/hooks/use-navigate)

2022-10-15 10:29 UTC, LinaYahya commented on client/src/components/jobCard/jobCard.tsx
> +          <h2 className="h2">
I would prefer to use typography mui component, Even If we want to keep use `h2` try to change `className`

2022-10-15 10:29 UTC, LinaYahya commented on client/src/components/jobCard/jobCard.tsx
> +import './jobCard.css';
rename files to `index.ts` and `style.css`

2022-10-15 15:10 UTC, mohammedagha27 approved these changes

2022-10-15 18:18 UTC, alishanti98 approved these changes

2022-10-16 07:39 UTC, naghamabuwarda approved these changes

2022-10-16 08:59 UTC, LinaYahya approved these changes

2022-10-16 09:00 UTC, merged