51 react create the search page and include its components
CA-G12/g-lancer pull request #71
Opened 2022-10-19 09:32 UTC by naghamabuwarda

2022-10-19 11:55 UTC, LinaYahya requested changes

2022-10-19 11:55 UTC, LinaYahya commented on client/src/components/filter/index.tsx
> +            value={location.state?.category || category}
```suggestion
            value={category}
            defaultValue={location.state?.category}```

2022-10-19 11:55 UTC, LinaYahya commented on client/src/components/filter/index.tsx
>            <label htmlFor="price" className="label">Price</label>
change label to Minimum budget, It'll be more descriptive

2022-10-19 11:55 UTC, LinaYahya commented on client/src/components/tab/index.tsx
> +  child: JSX.Element[];
```suggestion
 child: JSX.Element | JSX.Element[];
;
```

2022-10-19 12:28 UTC, LinaYahya requested changes

2022-10-19 12:28 UTC, LinaYahya commented on client/src/pages/JobsSearch/index.tsx
>    const [category, setCategory] = useState<string>('');
set the initial state as `(state?.category` || '')`

2022-10-20 06:25 UTC, shathakh approved these changes

2022-10-20 06:30 UTC, LinaYahya approved these changes

2022-10-20 07:01 UTC, mohammedagha27 approved these changes

2022-10-20 07:01 UTC, merged