feat: create the freelancer info card component and its style Close #74
CA-G12/g-lancer pull request #75
Opened 2022-10-19 12:05 UTC by mohammedagha27

2022-10-19 13:19 UTC, LinaYahya requested changes

2022-10-19 13:19 UTC, LinaYahya commented on client/src/components/FreelancerInfoCard/index.tsx
> +            <p className="freelancer-portfolio"><a href={info.portfolio}>Portfolio</a></p>
Not sure why this looks much bigger than it's relative p tags!

2022-10-19 13:19 UTC, LinaYahya commented on client/src/components/FreelancerInfoCard/index.tsx
> +            <h3 className="freelancer-name">{info.name}</h3>
```suggestion
            <h3 className="freelancer-name">{info.name}</h3> // make it bigger
```

2022-10-19 13:19 UTC, LinaYahya commented on client/src/components/FreelancerInfoCard/index.tsx
> +            <img src={info.image || avatar} alt="" />
```suggestion
            <img src={info.image || avatar} alt="add alt here" />
```

2022-10-19 13:19 UTC, LinaYahya commented on client/src/components/FreelancerInfoCard/index.tsx
> +        <Grid xs={10} sm={8} md={6} lg={4} item>
all fonts size need to be bigger alittle

2022-10-19 13:19 UTC, LinaYahya commented on client/src/components/FreelancerInfoCard/index.tsx
> +function FreelancerInfoCard({ info }: Props) {
render it at freelancer page and give it initial props

2022-10-23 08:07 UTC, alishanti98 approved these changes

2022-10-23 18:28 UTC, LinaYahya requested changes

2022-10-23 18:28 UTC, LinaYahya commented on client/src/validation/index.ts
> +  brief: yup.string()
brief is not required in our `database`, So it shouldn't be here!

2022-10-23 18:28 UTC, LinaYahya commented on client/src/validation/index.ts
> +  name: yup.string()
I think we have a title also as a freelancer info

2022-10-23 18:28 UTC, LinaYahya commented on client/src/pages/Freelancer/index.tsx
> +    brief: `Lottie is graduated
```suggestion
title, 
    brief: `Lottie is graduated
```

2022-10-24 06:26 UTC, LinaYahya approved these changes

2022-10-24 06:27 UTC, shathakh approved these changes

2022-10-24 06:29 UTC, naghamabuwarda approved these changes

2022-10-24 06:29 UTC, merged