77 single job page
CA-G12/g-lancer pull request #83
Opened 2022-10-20 12:51 UTC by shathakh

2022-10-21 10:36 UTC, alishanti98 approved these changes

2022-10-21 13:47 UTC, naghamabuwarda approved these changes

2022-10-21 13:50 UTC, mohammedagha27 approved these changes

2022-10-23 09:02 UTC, LinaYahya requested changes
Good Job Shatha,
small changes to fix and also handle proposal form onSubmit to send request to `POST /proposal`

2022-10-23 09:02 UTC, LinaYahya commented on client/src/pages/Job/index.tsx
> +      {jobState && <JobDetails job={jobState} client={client} handleClick={handleClick} /> }
```suggestion
      {<JobDetails job={jobState} client={client} handleClick={handleClick} /> }
```
NO need as the initial state it's not null anymore

2022-10-23 12:47 UTC, LinaYahya approved these changes

2022-10-23 12:47 UTC, merged