feat: create GET/ freelancer API with its tests
CA-G12/g-lancer pull request #98
Opened 2022-10-24 11:16 UTC by mohammedagha27

2022-10-24 11:29 UTC, LinaYahya requested changes

2022-10-24 11:29 UTC, LinaYahya commented on server/src/controllers/freelancer.ts
> +  return { status: 404, msg: 'Freelancer Not Found' };
```suggestion
  return { status: 400, msg: 'Freelancer Not Found' };
```

2022-10-24 12:06 UTC, alishanti98 approved these changes

2022-10-24 13:10 UTC, LinaYahya approved these changes

2022-10-25 06:27 UTC, naghamabuwarda approved these changes

2022-10-25 06:31 UTC, merged